<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="taurob_mi">
  <xacro:include filename="$(find taurob_mi_description)/urdf/inertia_tensors.urdf.xacro"/>
  <xacro:property name="base_size_x" value="${0.365*2}"/>
  <xacro:property name="base_size_y" value="0.24"/>
  <xacro:property name="base_size_z" value="0.312 "/>
  <xacro:property name="base_offset_x" value="-0.122"/>
  <xacro:property name="base_offset_z" value="-0.05"/>
  <xacro:macro name="tracker_chassis_macro">

    <link name="base_link"/>

    <joint name="chassis_joint" type="fixed">
      <origin xyz="${-base_offset_x} 0 0.18" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="chassis_link"/>
    </joint>

    <link name="flipper_link">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <collision>
        <origin xyz="0.5 -0.23 ${base_offset_z}" rpy="0 0 0"/>
        <geometry>
          <box size="1.05 0.14 0.35"/>
        </geometry>
      </collision>
      <collision>
        <origin xyz="0.5 0.23 ${base_offset_z}" rpy="0 0 0"/>
        <geometry>
          <box size="1.05 0.14 0.35"/>
        </geometry>
      </collision>
    </link>

    <joint name="flipper_front" type="revolute">
      <origin xyz="${base_offset_x-0.5} 0 0" rpy="0 0 0"/>
      <axis xyz="0 -1 0"/>
      <limit lower="${-30 * M_PI / 180}" upper="${50 * M_PI / 180}" effort="204" velocity="${1.0 * 110 * M_PI / 180}"/>
      <safety_controller soft_lower_limit="${-25 * M_PI / 180}" soft_upper_limit="${45 * M_PI / 180}" k_position="${100}" k_velocity="${2}"/>
      <parent link="chassis_link"/>
      <child link="flipper_link"/>
    </joint>

    <link name="chassis_link">
      <xacro:inertial_cuboid_with_pose mass="20" x_length="${base_size_x}" y_length="${base_size_y}" z_length="${base_size_z}">
        <origin xyz="0.0 0.0 ${0.312*0.5}" rpy="0 0 0"/>
      </xacro:inertial_cuboid_with_pose>
      <visual>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://taurob_mi_description/meshes/taurob/tracker_chassis.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="${base_offset_x-0.11} 0.0 ${base_offset_z}" rpy="0 0 0"/>
        <geometry>
          <box size="0.74 0.5 0.2"/>
        </geometry>
      </collision>
      <collision>
        <origin xyz="${base_offset_x} -0.23 ${base_offset_z}" rpy="0 0 0"/>
        <geometry>
          <box size="1.0 0.13 0.35"/>
        </geometry>
      </collision>
      <collision>
        <origin xyz="${base_offset_x} 0.23 ${base_offset_z}" rpy="0 0 0"/>
        <geometry>
          <box size="1.0 0.13 0.35"/>
        </geometry>
      </collision>
    </link>

  </xacro:macro>


<!-- gazebo ROS plugins -->

 <gazebo>


    <plugin name="p3d_base_controller" filename="libgazebo_ros_p3d.so">
      <alwaysOn>true</alwaysOn>
      <updateRate>50.0</updateRate>
      <bodyName>base_link</bodyName>
      <topicName>ground_truth/state</topicName>
      <gaussianNoise>0.01</gaussianNoise>
      <frameName>world</frameName>
      <xyzOffsets>0 0 0</xyzOffsets>
      <rpyOffsets>0 0 0</rpyOffsets>
    </plugin>


    <plugin name="imu_controller" filename="libhector_gazebo_ros_imu.so">
      <alwaysOn>true</alwaysOn>
      <updateRate>50.0</updateRate>
      <bodyName>base_link</bodyName>
      <topicName>/imu/data</topicName>
      <accelDrift>0.0 0.0 0.0</accelDrift>
      <accelGaussianNoise>0.1 0.1 0.1</accelGaussianNoise>
      <rateDrift>0.0 0.0 0.0</rateDrift>
      <rateGaussianNoise>0.05 0.05 0.05</rateGaussianNoise>
      <headingDrift>0.0</headingDrift>
      <headingGaussianNoise>0.05</headingGaussianNoise>
    </plugin>


<!-- We need to model the wheel joints for that and take some values from hector e.g. torque -->

  <plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
    <updateRate>100.0</updateRate>
    <robotNamespace>/</robotNamespace>
    <leftFrontJoint>front_left_wheel_joint</leftFrontJoint>
    <rightFrontJoint>front_right_wheel_joint</rightFrontJoint>
    <leftRearJoint>back_left_wheel_joint</leftRearJoint>
    <rightRearJoint>back_right_wheel_joint</rightRearJoint>
    <wheelSeparation>0.4</wheelSeparation>
    <wheelDiameter>0.215</wheelDiameter>
    <robotBaseFrame>base_link</robotBaseFrame>
    <torque>50000</torque>
    <topicName>cmd_vel</topicName>
    <broadcastTF>true</broadcastTF>
  </plugin> 


  </gazebo>

  
</robot>
