map_type: costmap    #"voxel" or "costmap"
robot_base_frame: base_link


#transform_tolerance: 0.2


footprint: [ [0.54, 0.31], [0.54, -0.31], [-0.47, -0.31], [-0.47, 0.31] ]


# layer definitions

static:
    map_topic: /map
    first_map_only: false

obstacles_laser:
    observation_sources: laser
    laser: {sensor frame: base_laser, data_type:  LaserScan, topic: scan, clearing: true, marking: true, raytrace_range: 5.0, obstacle_range: 5.0}

inflation:
    inflation_radius: 0.55


#scan: {sensor frame: base_laser, data_type: LaserScan, topic: scan_final, expected_update_rate: 0.4, marking: true, clearing: true, observation_persistence: 0.2, raytrace_range: 4.0, obstacle_range: 4.0}

