#Independent settings for the local planner's costmap. Detailed descriptions of these parameters can be found at http://www.ros.org/wiki/costmap_2d

global_frame: odom

update_frequency: 5
publish_frequency: 2.0

static_map: true
rolling_window: false
width: 6.0
height: 6.0
resolution: 0.025


plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}

